### ISSUE TITLE
Different color display in Sozi on Ubuntu

### ISSUE THREAD

**Issue by albertheres** [sozi-projects/Sozi#506]
# Colors in Inkscape are different displayed in Sozi.

I notice that a colors from my inkscape file are different displayed in Sozi. You can see it on this [screen capture](https://i.imgur.com/NA2Ju5k.png). 

- I have tested it on Ubuntu 64bit 20.04 with Sozi 20.05 and 20.11 as well. But no difference. 
- When I use Windows 10 64bit the colors are equal in Inkscape an Sozi. So it seems a Linux issue.

Assumed this is related to color profiles. But I don't know how to solve it.

**Comment by aumouvantsillage** [comment]
Have you tried to open the SVG alone in a web browser?

Sozi is not supposed to alter the visual rendering of your documents.
At first sight, I would consider that this is an issue in Inkscape or in the rendering engine that Sozi uses.

**Comment by albertheres** [comment]
Yes, I tried. The SVG is displayed equal in Inkscape and Firefox, but different in Sozi as you can see [here](https://i.imgur.com/vB4yXCO.png).

Also the slider bar is not blue displayed, but purple as you can see [here](https://i.imgur.com/7G6YnIK.png). This seems related

**Comment by albertheres** [comment]
Just some additional info that I discovered:

- SVG colors in Inkscape are **right** displayed
- SVG colors in Firefox are **right** displayed
- SVG colors in Sozi are **wrong** displayed (blue becomes purple)
- Sozi.html colors in Firefox are **right** displayed
- Sozi export to MP4 colors are **wrong** displayed (actually: wrong rendered)

This is a single [screen capture](https://i.imgur.com/bBR8hSo.png) with all samples included.

Hopefully there is a quick fix to solve this issue.

**Comment by aumouvantsillage** [comment]
Thanks for the additional info. This is very helpful.
I think that your problem is related to [this issue in Electron](https://github.com/electron/electron/issues/10732)

I will check whether the option `--disable-color-correct-rendering` works in the current version of Sozi.
If not, the only way to fix it consists in rebuilding Sozi against a fixed version of Electron.

**Comment by albertheres** [comment]
My pleasure! Indeed that Electron issue seems related. Thanks for checking that option. 

I have checked more colors (default inkscape swatches) and I notice that especially blue is affected as you can see [here](https://i.imgur.com/AgyiYcW.png).

**Comment by aumouvantsillage** [comment]
I have added the "disable-color-correct-rendering" option.
However, since I cannot reproduce your problem, I am not sure that it is fixed.

You can try it by running [this version for Linux x64](https://drive.google.com/file/d/1DHolNMwZT5gkJIEfVnD9HVqArK8-yz3O/view?usp=sharing)

**Comment by albertheres** [comment]
Thanks for you effort! unfortunately this does not solve the problem as you can see [here](https://i.imgur.com/BPNEBtf.png) :(

**Comment by albertheres** [comment]
I solved the problem as you can see [here](https://i.imgur.com/QThjJwg.png)! 

The monitor color profile was the trick. I changed it from **HP default** to **sRGB** and the colors are displayed equally now in Inkscape and Sozi. Check [this comment ](https://github.com/electron/electron/issues/10732#issuecomment-341481598)with more info.

**Comment by aumouvantsillage** [comment]
Great.
I would not consider it "solved" because I would expect Sozi to comply with any custom color profile.

**Comment by albertheres** [comment]
Yes I agree with you. I have a workaround that solved the issue for me. But a global solution is better. 

It is a conscious choice as you can read is the [document](https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40/edit#heading=h.suy812wv3k6a). 

> Chrome will assume that the operating system settings for color management were set intentionally, and will respect those settings.
